### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Rhylthus** [maocypher/Octoprint-Smart-Filament-Sensor#2]
Hi,

I have installed version 1.0.1 and it doesnt show up in octoprint plugins after installation. I'm on Python 3, so first version also doens't work. let me know if you need anithing to fix this. Thanks.

**Comment by maocypher** [comment]
Hi, did you restart Octoprint, like it is describe in the installation manual?

**Comment by Rhylthus** [comment]
Yes i have restart several time. I have also tried to install other plugin ans they work flawlessly. Any clue?

**Comment by maocypher** [comment]
I try to reproduce it. Is there also Python 2.x installed on your machine or only Python 3.x?

**Comment by Rhylthus** [comment]
Sorry i dont know. How can i check? Fyi first version was also not working.

**Comment by maocypher** [comment]
On your linux terminal you can try
- python2 --version
- ls /usr/bin/python*

to name to alternatives.

Your exact python3 and octoprint version would also be helpful for me

**Comment by Rhylthus** [comment]
Here you go 

OctoPrint version : 1.4.2
OctoPi version    : 0.17.0
------------------------------------------------------------------------------

python2 --version
Python 2.7.16
python3 --version
Python 3.7.3

Thanks.

**Comment by maocypher** [comment]
Okay, I have the same python versions, but I installed Octoprint on Raspbian and I am not running it on OctoPi image. But it is running without errors.
Could you take a look into **<your installation path>/.octoprint/logs/octoprint.log** after restarting Octoprint if you can see any errors or provide me the log?
After start up it should start with the following lines

``` BASH
2020-10-22 15:47:27,549 - octoprint.startup - INFO - ******************************************************************************
2020-10-22 15:47:27,550 - octoprint.startup - INFO - Starting OctoPrint 1.4.2
2020-10-22 15:47:27,551 - octoprint.startup - INFO - ******************************************************************************
```

**Comment by Rhylthus** [comment]
Here it is after a restart: seems bad?

2020-10-22 20:59:54,887 - octoprint.startup - INFO - ******************************************************************************
2020-10-22 20:59:54,889 - octoprint.startup - INFO - Starting OctoPrint 1.4.2
2020-10-22 20:59:54,894 - octoprint.startup - INFO - ******************************************************************************
2020-10-22 20:59:55,603 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: offline
2020-10-22 20:59:55,603 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 8.8.8.8:53 is not working
2020-10-22 20:59:55,603 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is not working
2020-10-22 20:59:55,611 - octoprint.startup - INFO - We don't appear to be online, not fetching plugin blacklist
2020-10-22 20:59:55,704 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-10-22 20:59:58,210 - octoprint.plugin.core - ERROR - Error loading plugin bedlevelvisualizer
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 972, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 71, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 241, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 215, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_bedlevelvisualizer/__init__.py", line 7, in <module>
    import numpy as np
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/home/pi/oprint/bin/python"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

2020-10-22 20:59:58,390 - octoprint.plugins.octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2020-10-22 20:59:58,413 - octoprint.plugin.core - INFO - Found 29 plugin(s) providing 29 mixin implementations, 57 hook handlers
2020-10-22 20:59:58,677 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2020-10-22 20:59:58,722 - octoprint.server - INFO - Intermediary server started
2020-10-22 20:59:58,723 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2020-10-22 20:59:58,868 - octoprint.plugin.core - ERROR - Error loading plugin bedlevelvisualizer
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 972, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 71, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 241, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 215, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_bedlevelvisualizer/__init__.py", line 7, in <module>
    import numpy as np
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/oprint/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/home/pi/oprint/bin/python"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

2020-10-22 20:59:58,874 - octoprint.plugin.core - INFO - Found 29 plugin(s) providing 29 mixin implementations, 57 hook handlers
2020-10-22 20:59:58,917 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2020-10-22 21:00:00,711 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2020-10-22 21:00:00,714 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_SHOW (needs: "Need(method='role', value='plugin_action_command_notification_show')")
2020-10-22 21:00:00,715 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_CLEAR (needs: "Need(method='role', value='plugin_action_command_notification_clear')")
2020-10-22 21:00:00,715 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: "Need(method='role', value='plugin_action_command_prompt_interact')")
2020-10-22 21:00:00,716 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: "Need(method='role', value='plugin_announcements_read')")
2020-10-22 21:00:00,716 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: "Need(method='role', value='plugin_announcements_manage'), Need(method='role', value='plugin_announcements_read')")
2020-10-22 21:00:00,717 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: "Need(method='role', value='plugin_appkeys_admin')")
2020-10-22 21:00:00,717 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: "Need(method='role', value='plugin_backup_access')")
2020-10-22 21:00:00,718 - octoprint.server - INFO - Added new permission from plugin firmware_check: PLUGIN_FIRMWARE_CHECK_DISPLAY (needs: "Need(method='role', value='plugin_firmware_check_display')")
2020-10-22 21:00:00,718 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: "Need(method='role', value='plugin_logging_manage')")
2020-10-22 21:00:00,718 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: "Need(method='role', value='plugin_pi_support_check')")
2020-10-22 21:00:00,719 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: "Need(method='role', value='plugin_pluginmanager_manage')")
2020-10-22 21:00:00,722 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: "Need(method='role', value='plugin_pluginmanager_manage'), Need(method='role', value='plugin_pluginmanager_install')")
2020-10-22 21:00:00,724 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: "Need(method='role', value='plugin_softwareupdate_check')")
2020-10-22 21:00:00,725 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: "Need(method='role', value='plugin_softwareupdate_update')")
2020-10-22 21:00:00,747 - octoprint.printer.standard - INFO - Using print time estimator provided by PrintTimeGenius
2020-10-22 21:00:01,962 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -m pip" as command to invoke pip
2020-10-22 21:00:02,938 - octoprint.util.pip - INFO - Version of pip is 20.2.3
2020-10-22 21:00:02,940 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-10-22 21:00:02,940 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-10-22 21:00:03,264 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2020-10-22 21:00:03,277 - octoprint.plugins.smartfilamentsensor - INFO - Running RPi.GPIO version '0.7.0'
2020-10-22 21:00:03,305 - octoprint.plugin.core - INFO - Initialized 29 plugin implementation(s)
2020-10-22 21:00:03,324 - octoprint.plugin.core - INFO - 29 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/appkeys
|  Arc-Welder (0.1.0rc1.dev4) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_arc_welder
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup
|  Change Filament Plugin (0.3.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_Change_Filament
|  Core Wizard (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/corewizard
|  Cura Thumbnails (0.2.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_ultimakerformatpackage
|  Discovery (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/discovery
|  DisplayLayerProgress Plugin (1.24.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_DisplayLayerProgress
|  Error Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/errortracking
|  File Check (2020.8.7) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_file_check
|  Firmware Check (2020.9.23) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmware_check
|  GCode Viewer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/gcodeviewer
|  GcodeEditor (0.2.9) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_GcodeEditor
|  Logging (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/logging
|  Login UI (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/loginui
|  Navbar Temperature Plugin (0.14) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_navbartemp
|  Octoprint-Display-ETA (1.1.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_display_eta
|  OctoPrint-WiFiStatus (1.3.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_wifistatus
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pluginmanager
|  PrintTimeGenius Plugin (2.2.6) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintTimeGenius
|  Smart Filament Sensor (1.0.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_smart_filament_sensor
|  Software Update (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate
|  TP-Link Smartplug (0.9.24) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_tplinksmartplug
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2020-10-22 21:00:03,342 - octoprint.environment - INFO - Detected environment is Python 3.7.3 under Linux (linux). Details:
|  hardware:
|      cores: 4
|      freq: 1200.0
|      ram: 917016576
|  os:
|      id: linux
|      platform: linux
|  plugins:
|      pi_support:
|          model: Raspberry Pi 3 Model B Rev 1.2
|          octopi_version: 0.17.0
|  python:
|      pip: 20.2.3
|      version: 3.7.3
|      virtualenv: /home/pi/oprint
2020-10-22 21:00:03,357 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2020-10-22 21:00:03,380 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2020-10-22 21:00:04,532 - octoprint.server - INFO - Shutting down intermediary server...
2020-10-22 21:00:04,868 - octoprint.server - INFO - Intermediary server shut down
2020-10-22 21:00:04,870 - octoprint.events - INFO - Processing startup event, this is our first event
2020-10-22 21:00:04,871 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2020-10-22 21:00:04,875 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2020-10-22 21:00:04,875 - octoprint.server - INFO - Autoconnect on startup is configured, trying to connect to the printer...
2020-10-22 21:00:04,991 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2020-10-22 21:00:05,059 - octoprint.server - INFO - Trying to connect to configured serial port None
2020-10-22 21:00:05,144 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Detecting serial connection"
2020-10-22 21:00:05,152 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2020-10-22 21:00:05,153 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2020-10-22 21:00:05,175 - octoprint.util.comm - INFO - Serial detection: Performing autodetection with 1 port/baudrate candidates: /dev/ttyUSB0@250000
2020-10-22 21:00:05,175 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 250000
2020-10-22 21:00:05,176 - octoprint.util.comm - INFO - Connecting to port /dev/ttyUSB0, baudrate 250000
2020-10-22 21:00:05,184 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2020-10-22 21:00:05,203 - octoprint.plugins.pi_support - WARNING - This Raspberry Pi is reporting problems that might lead to bad performance or errors caused by overheating or insufficient power.
!!! UNDERVOLTAGE REPORTED !!! Make sure that the power supply and power cable are capable of supplying enough voltage and current to your Pi.
2020-10-22 21:00:05,211 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2020-10-22 21:00:05,220 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-10-22 21:00:05,915 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2020-10-22 21:00:05,984 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2020-10-22 21:00:07,114 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -m pip" as command to invoke pip
2020-10-22 21:00:07,131 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2020-10-22 21:00:07,131 - octoprint.util.pip - INFO - ==> pip ok -> yes
2020-10-22 21:00:07,163 - octoprint.plugins.softwareupdate - INFO - Minimum free storage across all update relevant locations is 8.5GB. That is considered sufficient for updating.
2020-10-22 21:00:07,247 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2020-10-22 21:00:07,339 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2020-10-22 21:00:07,675 - octoprint.plugins.smartfilamentsensor - INFO - Smart Filament Sensor started
2020-10-22 21:00:07,675 - octoprint.plugins.smartfilamentsensor - INFO - Pins not configured, won't work unless configured!
2020-10-22 21:00:07,676 - octoprint.plugins.tplinksmartplug - INFO - TPLinkSmartplug loaded!
2020-10-22 21:00:07,694 - octoprint.plugins.wifistatus - INFO - WiFiStatus loaded!
2020-10-22 21:00:07,776 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2020-10-22 21:00:07,878 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-10-22 21:00:08,636 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.0.172
2020-10-22 21:00:09,418 - octoprint.server.util.flask - INFO - Passively logging in user Greg from ::ffff:192.168.0.172
2020-10-22 21:00:09,419 - octoprint.access.users - INFO - Logged in user: Greg
2020-10-22 21:00:09,513 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2020-10-22 21:00:09,647 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'base_url': 'http://192.168.0.194/', 'path': '/', 'query_string': 'l10n=en'}
2020-10-22 21:00:09,848 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2020-10-22 21:00:09,878 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-10-22 21:00:10,732 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2020-10-22 21:00:11,870 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial connection" to "Error: No more candidates to test, and no working port/baudrate combination detected."
2020-10-22 21:00:11,877 - octoprint.plugins.smartfilamentsensor - INFO - Error: Disabling filament sensors.
2020-10-22 21:00:11,879 - octoprint.util.comm - INFO - Changing monitoring state from "Error: No more candidates to test, and no working port/baudrate combination detected." to "Offline (Error: No more candidates to test, and no working port/baudrate combination detected.)"
2020-10-22 21:00:11,893 - octoprint.plugins.action_command_notification - INFO - Notifications cleared

**Comment by Rhylthus** [comment]
I have re-install on a fresh sd card octoprint and this plugin and everithing is working. So it must be something messing from my side. Thanks for your help.
